export const PAGE_URL = {
  ROOT: '/',
  NOT_FOUND: '*',
  SIGN_IN: '/auth/signin',
  SIGN_UP: '/auth/signup',
  MYSTAT: '/mystat',
  MYPAGE: '/mypage',
  SEARCHBOOK: '/book/search',
  POSTBOOK: '/book/register/:id',
  DETAILBOOKINFO: '/book/detail/:id',
  RECOMMENDEDBOOKS: '/book/recommended',
  LIBRARY: '/book/library',
  LIBRARYBOOK: '/book/library/:bookId',
  MEMO_FORM: '/book/library/:bookId/memo',
  EDIT_MEMO: '/book/library/:bookId/memo/:memoId',
  MEMO_BOOK: '/memobook',
  COMMUNITY: '/community',
} as const;
